application: omniweblog
version: 1
runtime: python
api_version: 1

handlers:
- url: /static/
  static_dir: static

- url: /fonts/(.*\.otf)
  static_files: static/fonts/\1
  mime_type: font/opentype
  upload: /fonts/(.*\.otf)

- url: /tasks/searchindexing
  script: blog.py
  login: admin

- url: /.*
  script: blog.py
