application: tornado-appengine
version: 1
runtime: python
api_version: 1

handlers:
- url: /static/
  static_dir: static

- url: /tasks/searchindexing
  script: blog.py
  login: admin

- url: /.*
  script: blog.py
